import numpy as np

from controller import DroneController
from sensors import GPSSensor, CameraSensor


class Drone:
    """
    Autonomous drone agent for distributed occupancy-grid mapping.

    Responsibilities
    ----------------
    - maintain its physical state;
    - acquire measurements through its sensors;
    - store the latest sensing information;
    - update its local occupancy grid;
    - apply control actions generated by its onboard DroneController.
    """

    def __init__(
        self,
        drone_id,
        x,
        y,
        grid_shape,
        grid_bounds,
        sensor_size=100,
        gps_noise=0.03,
        camera_noise=0.03,
        max_speed=0.12,
        occupancy_threshold=0.6,
        controller=None,
    ):

        self.drone_id = drone_id

        self.x = float(x)
        self.y = float(y)

        self.max_speed = float(max_speed)

        self.grid_shape = tuple(grid_shape)
        self.grid_bounds = tuple(grid_bounds)

        self.x_min, self.x_max, self.y_min, self.y_max = self.grid_bounds

        self.Nx, self.Ny = self.grid_shape

        self.grid = np.full(self.grid_shape, 0.5, dtype=float)
        self.occupancy_signal_grid = np.zeros(self.grid_shape, dtype=float)
        self.information_grid = np.zeros(self.grid_shape, dtype=float)
        self.boundary_grid = np.zeros(self.grid_shape, dtype=float)
        self.gps = GPSSensor(noise_std=gps_noise)
        self.camera = CameraSensor(
            size=sensor_size,
            noise_std=camera_noise,
            occupancy_threshold=occupancy_threshold,
        )
        self.last_gps_position = np.asarray(self.get_gps_pos(), dtype=float)

        self.edge_detected = False
        self.last_edge_point = None
        self.last_edge_points = np.empty((0, 2), dtype=float)
        self.last_nls_points = np.empty((0, 2), dtype=float)
        self.last_boundary_anchor_point = None
        self.last_edge_count = 0
        self.last_oil_fraction = None
        self.last_camera_image = None
        self.last_camera_spacing = None
        self.last_camera_center_position = None
        self.last_camera_source_bounds = None
        self.last_mapped_boundary_points = np.empty((0, 2), dtype=float)
        self.last_control_mode = "idle"
        self.last_control_vector = np.zeros(2, dtype=float)
        self.last_mapping_tangent = None
        self.control_state = "mapping"
        self.known_positions = {
            self.drone_id: self.last_gps_position.copy(),
        }
        self.known_boundary_arcs = {}
        self.known_boundary_points = np.empty((0, 2), dtype=float)
        self.boundary_index = None
        self.boundary_s = None
        self.pending_boundary_s = None
        self.pending_boundary_point = None
        self.target_centroid = None
        self.last_ring_info = None

        self.exploration_direction = self._random_unit_direction()
        self.controller = controller
        if self.controller is None:
            self.controller = DroneController(
                sim_map=None,
                communication_radius=0.0,
            )

    def compute_action(
        self,
        world_field=None,
        x_coords=None,
        y_coords=None,
    ):
        return self.controller.compute_action(
            self,
            world_field,
            x_coords,
            y_coords,
        )

    def set_known_boundary(
        self,
        boundary_points,
        known_boundary_closed=True,
        already_ordered=True,
    ):
        self.known_boundary_points = np.asarray(boundary_points, dtype=float).copy()
        self.controller.set_known_boundary(
            self.known_boundary_points,
            known_boundary_closed=known_boundary_closed,
            already_ordered=already_ordered,
        )

    def project_to_boundary(self):
        self.controller.project_to_boundary(self)

    def update_boundary_projection(self):
        self.controller.update_boundary_projection(self)

    def create_consensus_message(self):
        """
        Return the local map payload broadcast by this drone.
        """
        return {
            "sender_id": self.drone_id,
            "grid": np.asarray(self.grid, dtype=float).copy(),
            "signal_grid": np.asarray(self.occupancy_signal_grid, dtype=float).copy(),
            "information_grid": np.asarray(self.information_grid, dtype=float).copy(),
        }

    @property
    def position(self):
        """Return the current drone position as [x, y]."""
        return np.array([self.x, self.y], dtype=float)

    def get_gps_pos(self):
        """
        Return the current position measured by the GPS sensor.
        """
        return self.gps.sense(self.position)

    def update_position_estimate(self):
        """Acquire and store the latest GPS-based position estimate."""
        self.last_gps_position = np.asarray(self.get_gps_pos(), dtype=float)
        return self.last_gps_position.copy()

    def sense(
        self,
        world_field,
        x_coords,
        y_coords,
    ):
        """
        Acquire a camera measurement.

        CameraSensor is responsible for obtaining the local measurement
        and performing edge detection.

        Returns
        -------
        np.ndarray
            Detected edge points in global coordinates.
        """

        position_estimate = self.update_position_estimate()

        measurement = self.camera.sense(
            world_field=world_field,
            x=position_estimate[0],
            y=position_estimate[1],
            x_coords=x_coords,
            y_coords=y_coords,
            position_estimate=position_estimate,
        )
        if measurement is None:
            self._clear_sensing_state()
            self.last_camera_image = None
            self.last_camera_spacing = None
            self.last_camera_center_position = None
            self.last_camera_source_bounds = None
            return self.last_edge_points

        if hasattr(measurement, "image"):
            self.last_camera_image = np.asarray(measurement.image, dtype=float).copy()
            dx = float(x_coords[1] - x_coords[0]) if len(x_coords) > 1 else 1.0
            dy = float(y_coords[1] - y_coords[0]) if len(y_coords) > 1 else 1.0
            self.last_camera_spacing = (abs(dx), abs(dy))
            x_coords_arr = np.asarray(x_coords, dtype=float)
            y_coords_arr = np.asarray(y_coords, dtype=float)
            i_center = int(round((position_estimate[0] - x_coords_arr[0]) / dx))
            j_center = int(round((position_estimate[1] - y_coords_arr[0]) / dy))
            i_center = int(np.clip(i_center, 0, len(x_coords_arr) - 1))
            j_center = int(np.clip(j_center, 0, len(y_coords_arr) - 1))
            self.last_camera_center_position = np.array(
                [x_coords_arr[i_center], y_coords_arr[j_center]],
                dtype=float,
            )
            self.last_camera_source_bounds = (
                float(np.min(x_coords_arr)),
                float(np.max(x_coords_arr)),
                float(np.min(y_coords_arr)),
                float(np.max(y_coords_arr)),
            )

        if hasattr(measurement, "edge_points"):
            edge_points = np.asarray(measurement.edge_points, dtype=float)
            oil_fraction = getattr(measurement, "oil_fraction", None)
        else:
            edge_points = np.empty((0, 2), dtype=float)
            oil_fraction = None

        if edge_points.size == 0:
            self._clear_sensing_state()
            self.last_oil_fraction = oil_fraction
            return self.last_edge_points

        edge_points = edge_points.reshape(-1, 2)

        self.edge_detected = True
        self.last_edge_points = edge_points.copy()
        self.last_nls_points = edge_points.copy()
        self.last_edge_count = int(edge_points.shape[0])
        self.last_oil_fraction = oil_fraction

        current_anchor = np.mean(edge_points, axis=0)

        if self.last_boundary_anchor_point is None:
            self.last_boundary_anchor_point = current_anchor
        else:
            previous_anchor = np.asarray(self.last_boundary_anchor_point, dtype=float)
            self.last_boundary_anchor_point = (
                0.8 * previous_anchor + 0.2 * current_anchor
            )

        distances = np.linalg.norm(edge_points - self.last_gps_position, axis=1)
        nearest_idx = int(np.argmin(distances))
        nearest_point = edge_points[nearest_idx]
        self.last_edge_point = (float(nearest_point[0]), float(nearest_point[1]))

        return self.last_edge_points

    def _clear_sensing_state(self):
        """Clear transient sensing information."""
        self.edge_detected = False
        self.last_edge_points = np.empty((0, 2), dtype=float)
        self.last_nls_points = np.empty((0, 2), dtype=float)
        self.last_edge_count = 0
        self.last_edge_point = None

    def update_grid(
        self,
        edge_points,
        x_min,
        y_min,
        resolution,
        alpha=None,
        point_radius_cells=0,
        occupancy_threshold=0.6,
        x_coords=None,
        y_coords=None,
    ):
        """
        Fuse the latest camera footprint into the local occupancy grid.

        The occupancy estimate is probabilistic.  Cells observed by the camera
        receive a local binary oil/no-oil measurement, while never-observed
        cells remain unknown through ``information_grid == 0``.
        """
        del alpha, point_radius_cells, x_coords, y_coords

        if self.last_camera_image is not None:
            return self._update_grid_from_camera(
                x_min=x_min,
                y_min=y_min,
                resolution=resolution,
                occupancy_threshold=occupancy_threshold,
            )

        return self._update_grid_from_points(
            edge_points=edge_points,
            x_min=x_min,
            y_min=y_min,
            resolution=resolution,
            occupancy_threshold=occupancy_threshold,
        )

    def _update_grid_from_points(
        self,
        edge_points,
        x_min,
        y_min,
        resolution,
        occupancy_threshold,
    ):
        """Fallback for legacy point-only measurements."""
        if edge_points is None:
            return 0
        points = np.asarray(edge_points, dtype=float)

        if points.size == 0:
            return 0

        points = points.reshape(-1, 2)
        valid_updates = 0

        for x, y in points:
            ix = int((x - x_min) / resolution)
            iy = int((y - y_min) / resolution)

            if 0 <= ix < self.Nx and 0 <= iy < self.Ny:
                self.occupancy_signal_grid[ix, iy] = 1.0
                self.information_grid[ix, iy] = 1.0
                valid_updates += 1

        if valid_updates == 0:
            return 0

        self._refresh_probability_grid(occupancy_threshold=occupancy_threshold)

        return valid_updates

    def _update_grid_from_camera(
        self,
        x_min,
        y_min,
        resolution,
        occupancy_threshold,
    ):
        image = np.asarray(self.last_camera_image, dtype=float)
        if image.ndim != 2 or image.size == 0:
            return 0

        spacing = self.last_camera_spacing
        center = self.last_camera_center_position
        if spacing is None or center is None:
            return 0

        dx, dy = spacing
        dx = max(abs(float(dx)), 1e-12)
        dy = max(abs(float(dy)), 1e-12)
        center = np.asarray(center, dtype=float)
        if center.shape != (2,) or not np.all(np.isfinite(center)):
            return 0

        rows, cols = np.indices(image.shape)
        center_row = (image.shape[0] - 1) / 2.0
        center_col = (image.shape[1] - 1) / 2.0

        world_x = center[0] + (rows.astype(float) - center_row) * dx
        world_y = center[1] + (cols.astype(float) - center_col) * dy

        valid = np.isfinite(image)
        source_bounds = self.last_camera_source_bounds
        if source_bounds is not None:
            sx_min, sx_max, sy_min, sy_max = source_bounds
            valid &= (
                (world_x >= sx_min)
                & (world_x <= sx_max)
                & (world_y >= sy_min)
                & (world_y <= sy_max)
            )

        ix = np.floor((world_x - float(x_min)) / float(resolution)).astype(int)
        iy = np.floor((world_y - float(y_min)) / float(resolution)).astype(int)
        valid &= (0 <= ix) & (ix < self.Nx) & (0 <= iy) & (iy < self.Ny)

        if not np.any(valid):
            return 0

        flat_idx = ix[valid] * self.Ny + iy[valid]
        oil_pixels = (image[valid] >= float(occupancy_threshold)).astype(float)

        cell_count = np.bincount(flat_idx, minlength=self.Nx * self.Ny)
        oil_count = np.bincount(
            flat_idx,
            weights=oil_pixels,
            minlength=self.Nx * self.Ny,
        )
        observed = cell_count > 0
        if not np.any(observed):
            return 0

        measurement = np.zeros(self.Nx * self.Ny, dtype=float)
        measurement[observed] = oil_count[observed] / cell_count[observed]
        measurement = measurement.reshape(self.grid_shape)
        observed = observed.reshape(self.grid_shape)

        self.occupancy_signal_grid[observed] = measurement[observed]
        self.information_grid[observed] = 1.0
        self._refresh_probability_grid(occupancy_threshold=occupancy_threshold)

        return int(np.count_nonzero(observed))

    @staticmethod
    def probability_from_signal(
        signal_grid,
        information_grid,
        unknown_probability=0.5,
    ):
        signal = np.asarray(signal_grid, dtype=float)
        information = np.asarray(information_grid, dtype=float)
        probability = np.full(signal.shape, float(unknown_probability), dtype=float)
        valid = information > 1e-12
        probability[valid] = signal[valid] / information[valid]
        return np.clip(probability, 0.0, 1.0)

    @staticmethod
    def boundary_mask_from_probability(
        probability_grid,
        information_grid=None,
        occupancy_threshold=0.6,
        known_threshold=1e-12,
    ):
        probability = np.asarray(probability_grid, dtype=float)
        if information_grid is None:
            known = np.ones_like(probability, dtype=bool)
        else:
            known = np.asarray(information_grid, dtype=float) > float(known_threshold)

        occupied = (probability >= float(occupancy_threshold)) & known
        known_free = (probability < float(occupancy_threshold)) & known

        padded_free = np.pad(known_free, 1, mode="constant", constant_values=False)
        neighbor_free = np.zeros_like(known_free, dtype=bool)
        for dx in (-1, 0, 1):
            for dy in (-1, 0, 1):
                if dx == 0 and dy == 0:
                    continue
                neighbor_free |= padded_free[
                    1 + dx : 1 + dx + known_free.shape[0],
                    1 + dy : 1 + dy + known_free.shape[1],
                ]

        return occupied & neighbor_free

    def _grid_resolution(self):
        x_resolution = (self.x_max - self.x_min) / max(int(self.Nx), 1)
        y_resolution = (self.y_max - self.y_min) / max(int(self.Ny), 1)
        return 0.5 * (abs(float(x_resolution)) + abs(float(y_resolution)))

    def _boundary_points_from_mask(self, boundary_mask):
        cells = np.argwhere(np.asarray(boundary_mask, dtype=bool))
        if cells.size == 0:
            return np.empty((0, 2), dtype=float)

        resolution = self._grid_resolution()
        return np.column_stack(
            (
                self.x_min + (cells[:, 0] + 0.5) * resolution,
                self.y_min + (cells[:, 1] + 0.5) * resolution,
            )
        ).astype(float)

    def _refresh_probability_grid(self, occupancy_threshold=0.6):
        self.grid = self.probability_from_signal(
            self.occupancy_signal_grid,
            self.information_grid,
        )
        boundary_mask = self.boundary_mask_from_probability(
            self.grid,
            self.information_grid,
            occupancy_threshold=occupancy_threshold,
        )
        self.boundary_grid = boundary_mask.astype(float)
        self.last_mapped_boundary_points = self._boundary_points_from_mask(boundary_mask)
        return self.grid

    def consensus_step(
        self,
        neighbor_messages,
        own_grid=None,
        own_signal_grid=None,
        own_information_grid=None,
        occupancy_threshold=0.6,
    ):
        """
        Merge local occupancy with maps received from neighboring drones.

        Parameters
        ----------
        neighbor_messages : iterable
            Messages received from neighboring drones. Each message must contain
            a ``grid`` payload.

        own_grid : np.ndarray or None
            Optional snapshot of this drone's grid.

        Returns
        -------
        np.ndarray
            Updated local grid.
        """

        if own_grid is None:
            own_grid = self.grid
        if own_signal_grid is None or own_information_grid is None:
            own_signal_grid, own_information_grid = self._signal_information_from_message(
                {
                    "grid": own_grid,
                    "signal_grid": own_signal_grid,
                    "information_grid": own_information_grid,
                }
            )

        signals = [np.asarray(own_signal_grid, dtype=float)]
        information = [np.asarray(own_information_grid, dtype=float)]

        for message in neighbor_messages:
            signal_grid, information_grid = self._signal_information_from_message(message)
            if signal_grid is None or information_grid is None:
                continue

            signals.append(signal_grid)
            information.append(information_grid)

        if len(signals) == 1:
            self.occupancy_signal_grid = signals[0].copy()
            self.information_grid = information[0].copy()
            self._refresh_probability_grid(occupancy_threshold=occupancy_threshold)
            return self.grid

        self.occupancy_signal_grid = np.mean(signals, axis=0)
        self.information_grid = np.mean(information, axis=0)
        self._refresh_probability_grid(occupancy_threshold=occupancy_threshold)

        return self.grid

    def _signal_information_from_message(self, message):
        signal_grid = message.get("signal_grid")
        information_grid = message.get("information_grid")
        if signal_grid is not None and information_grid is not None:
            return (
                np.asarray(signal_grid, dtype=float),
                np.asarray(information_grid, dtype=float),
            )

        grid = message.get("grid")
        if grid is None:
            return None, None

        grid = np.asarray(grid, dtype=float)
        information_grid = (np.abs(grid - 0.5) > 1e-12).astype(float)
        signal_grid = grid * information_grid
        return signal_grid, information_grid

    def action(
        self,
        command,
        dt=1.0,
        bounds=None,
    ):
        """
        Apply a velocity-like command to the drone.

        Parameters
        ----------
        command : array-like
            Desired [vx, vy] command.

        dt : float
            Integration timestep.

        bounds : tuple or None
            Optional simulation bounds:

                ((x_min, x_max), (y_min, y_max))

            If omitted, the grid bounds are used.

        Returns
        -------
        np.ndarray
            Actual clipped command applied to the drone.
        """

        command = np.asarray(command, dtype=float)

        if command.shape != (2,) or not np.all(np.isfinite(command)):
            command = np.zeros(2, dtype=float)

        command = self._clip_command(command, self.max_speed)

        self.last_control_vector = command.copy()
        self.x += command[0] * float(dt)
        self.y += command[1] * float(dt)

        if bounds is None:
            x_bounds = (self.x_min, self.x_max)
            y_bounds = (self.y_min, self.y_max)
        else:
            x_bounds, y_bounds = bounds

        self.x = float(np.clip(self.x, x_bounds[0], x_bounds[1]))
        self.y = float(np.clip(self.y, y_bounds[0], y_bounds[1]))
        self.known_positions[self.drone_id] = self.last_gps_position.copy()

        return command

    def set_control_mode(self, mode):
        """
        Store the control mode selected by the onboard controller.
        """
        self.last_control_mode = str(mode)

    @staticmethod
    def _random_unit_direction():
        """Generate a random normalized 2D direction."""

        angle = np.random.uniform(0.0, 2.0 * np.pi)
        return np.array([np.cos(angle), np.sin(angle)], dtype=float)

    @staticmethod
    def _clip_command(
        command,
        max_speed,
    ):
        """Limit the magnitude of a 2D command."""

        vec = np.asarray(command, dtype=float)

        if vec.shape != (2,) or not np.all(np.isfinite(vec)):
            return np.zeros(2, dtype=float)

        speed = float(np.linalg.norm(vec))

        if speed <= 1e-12:
            return np.zeros(2, dtype=float)

        if speed > max_speed:
            vec = vec * (max_speed / speed)

        return vec
