import numpy as np

from controller import DroneController
from sensors import GPSSensor, CameraSensor


class Drone:
    """
    Autonomous drone agent for distributed occupancy-grid mapping.

    Responsibilities
    ----------------
    - maintain its physical state;
    - acquire measurements through its sensors;
    - store the latest sensing information;
    - update its local occupancy grid;
    - apply control actions generated by its onboard DroneController.
    """

    def __init__(
        self,
        drone_id,
        x,
        y,
        grid_shape,
        grid_bounds,
        sensor_size=100,
        gps_noise=0.03,
        camera_noise=0.03,
        max_speed=0.12,
        controller=None,
    ):

        self.drone_id = drone_id

        self.x = float(x)
        self.y = float(y)

        self.max_speed = float(max_speed)

        self.grid_shape = tuple(grid_shape)
        self.grid_bounds = tuple(grid_bounds)

        self.x_min, self.x_max, self.y_min, self.y_max = self.grid_bounds

        self.Nx, self.Ny = self.grid_shape

        self.grid = np.zeros(self.grid_shape, dtype=float)
        self.gps = GPSSensor(noise_std=gps_noise)
        self.camera = CameraSensor(size=sensor_size, noise_std=camera_noise)

        self.edge_detected = False
        self.last_edge_point = None
        self.last_edge_points = np.empty((0, 2), dtype=float)
        self.last_nls_points = np.empty((0, 2), dtype=float)
        self.last_boundary_anchor_point = None
        self.last_edge_count = 0
        self.last_oil_fraction = None
        self.last_control_mode = "idle"
        self.last_control_vector = np.zeros(2, dtype=float)

        self.exploration_direction = self._random_unit_direction()
        self.controller = controller
        if self.controller is None:
            self.controller = DroneController(
                sim_map=None,
                communication_radius=0.0,
            )

    def compute_action(
        self,
        world_field,
        x_coords,
        y_coords,
    ):
        return self.controller.compute_action(
            self,
            world_field,
            x_coords,
            y_coords,
        )

    def create_consensus_message(self):
        """
        Return the local map payload broadcast by this drone.
        """
        return {
            "sender_id": self.drone_id,
            "grid": np.asarray(self.grid, dtype=float).copy(),
        }

    @property
    def position(self):
        """Return the current drone position as [x, y]."""
        return np.array([self.x, self.y], dtype=float)

    def get_gps_pos(self):
        """
        Return the current position measured by the GPS sensor.
        """
        return self.gps.sense(self.position)

    def sense(
        self,
        world_field,
        x_coords,
        y_coords,
    ):
        """
        Acquire a camera measurement.

        CameraSensor is responsible for obtaining the local measurement
        and performing edge detection.

        Returns
        -------
        np.ndarray
            Detected edge points in global coordinates.
        """

        measurement = self.camera.sense(
            world_field=world_field,
            x=self.x,
            y=self.y,
            x_coords=x_coords,
            y_coords=y_coords,
        )
        if measurement is None:
            self._clear_sensing_state()
            return self.last_edge_points

        if hasattr(measurement, "edge_points"):
            edge_points = np.asarray(measurement.edge_points, dtype=float)
            oil_fraction = getattr(measurement, "oil_fraction", None)
        else:
            edge_points = np.empty((0, 2), dtype=float)
            oil_fraction = None

        if edge_points.size == 0:
            self._clear_sensing_state()
            self.last_oil_fraction = oil_fraction
            return self.last_edge_points

        edge_points = edge_points.reshape(-1, 2)

        self.edge_detected = True
        self.last_edge_points = edge_points.copy()
        self.last_nls_points = edge_points.copy()
        self.last_edge_count = int(edge_points.shape[0])
        self.last_oil_fraction = oil_fraction

        current_anchor = np.mean(edge_points, axis=0)

        if self.last_boundary_anchor_point is None:
            self.last_boundary_anchor_point = current_anchor
        else:
            previous_anchor = np.asarray(self.last_boundary_anchor_point, dtype=float)
            self.last_boundary_anchor_point = (
                0.8 * previous_anchor + 0.2 * current_anchor
            )

        distances = np.linalg.norm(edge_points - self.position, axis=1)
        nearest_idx = int(np.argmin(distances))
        nearest_point = edge_points[nearest_idx]
        self.last_edge_point = (float(nearest_point[0]), float(nearest_point[1]))

        return self.last_edge_points

    def _clear_sensing_state(self):
        """Clear transient sensing information."""
        self.edge_detected = False
        self.last_edge_points = np.empty((0, 2), dtype=float)
        self.last_nls_points = np.empty((0, 2), dtype=float)
        self.last_edge_count = 0
        self.last_edge_point = None

    def update_grid(
        self,
        edge_points,
        x_min,
        y_min,
        resolution,
        alpha=None,
    ):
        """
        Fuse detected edge points into the local occupancy grid as a binary map.

        Temporal smoothing is intentionally disabled: occupancy is represented as
        either 0 (empty) or 1 (occupied), without alpha-based blending.
        """

        if edge_points is None:
            return 0

        points = np.asarray(edge_points, dtype=float)

        if points.size == 0:
            return 0

        points = points.reshape(-1, 2)
        measurement_grid = np.zeros_like(self.grid)
        valid_updates = 0

        for x, y in points:
            ix = int((x - x_min) / resolution)
            iy = int((y - y_min) / resolution)

            if 0 <= ix < self.Nx and 0 <= iy < self.Ny:
                measurement_grid[ix, iy] += 1.0
                valid_updates += 1

        if valid_updates == 0:
            return 0

        self.grid = (np.maximum(self.grid, measurement_grid) > 0.0).astype(float)

        return valid_updates

    def consensus_step(
        self,
        neighbor_messages,
        own_grid=None,
    ):
        """
        Merge local occupancy with maps received from neighboring drones.

        Parameters
        ----------
        neighbor_messages : iterable
            Messages received from neighboring drones. Each message must contain
            a ``grid`` payload.

        own_grid : np.ndarray or None
            Optional snapshot of this drone's grid.

        Returns
        -------
        np.ndarray
            Updated local grid.
        """

        if own_grid is None:
            base_grid = self.grid
        else:
            base_grid = np.asarray(own_grid, dtype=float)

        grids = [np.asarray(base_grid, dtype=float)]

        for message in neighbor_messages:
            grid = message.get("grid")
            if grid is None:
                continue

            grids.append(np.asarray(grid, dtype=float))

        if len(grids) == 1:
            self.grid = (base_grid > 0.0).astype(float)
            return self.grid

        self.grid = (np.maximum.reduce(grids) > 0.0).astype(float)

        return self.grid

    def action(
        self,
        command,
        dt=1.0,
        bounds=None,
    ):
        """
        Apply a velocity-like command to the drone.

        Parameters
        ----------
        command : array-like
            Desired [vx, vy] command.

        dt : float
            Integration timestep.

        bounds : tuple or None
            Optional simulation bounds:

                ((x_min, x_max), (y_min, y_max))

            If omitted, the grid bounds are used.

        Returns
        -------
        np.ndarray
            Actual clipped command applied to the drone.
        """

        command = np.asarray(command, dtype=float)

        if command.shape != (2,) or not np.all(np.isfinite(command)):
            command = np.zeros(2, dtype=float)

        command = self._clip_command(command, self.max_speed)

        self.last_control_vector = command.copy()
        self.x += command[0] * float(dt)
        self.y += command[1] * float(dt)

        if bounds is None:
            x_bounds = (self.x_min, self.x_max)
            y_bounds = (self.y_min, self.y_max)
        else:
            x_bounds, y_bounds = bounds

        self.x = float(np.clip(self.x, x_bounds[0], x_bounds[1]))
        self.y = float(np.clip(self.y, y_bounds[0], y_bounds[1]))

        return command

    def set_control_mode(self, mode):
        """
        Store the control mode selected by the onboard controller.
        """
        self.last_control_mode = str(mode)

    @staticmethod
    def _random_unit_direction():
        """Generate a random normalized 2D direction."""

        angle = np.random.uniform(0.0, 2.0 * np.pi)
        return np.array([np.cos(angle), np.sin(angle)], dtype=float)

    @staticmethod
    def _clip_command(
        command,
        max_speed,
    ):
        """Limit the magnitude of a 2D command."""

        vec = np.asarray(command, dtype=float)

        if vec.shape != (2,) or not np.all(np.isfinite(vec)):
            return np.zeros(2, dtype=float)

        speed = float(np.linalg.norm(vec))

        if speed <= 1e-12:
            return np.zeros(2, dtype=float)

        if speed > max_speed:
            vec = vec * (max_speed / speed)

        return vec
